@ECHO OFF
CLS
ECHO **********************************************
ECHO *                                            *
ECHO *  ATUALIZANDO O SISTEMA AEREO. AGUARDE !  *
ECHO *                                            *
ECHO **********************************************
ECHO .
ECHO .
ECHO ON
COPY F:\AEREO\AEREO.EXE
@ECHO OFF
ECHO .
ECHO .
ECHO **********************************************************
ECHO *                                                        *
ECHO *  ACIMA DEVE TER A INFORMACAO: 1 arquivo(s) copiado(s). * 
ECHO *  CASO NAO TENHA ESTA INFORMACAO, SOLICITE SUPORTE      *
ECHO *  TECNICO. ESTA JANELA JA PODE SER FECHADA.             *
ECHO *                                                        *
ECHO **********************************************************
